# Generated by Django 6.0.1 on 2026-01-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('error_type', models.CharField(max_length=100)),
                ('error_code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='access.accesses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
