# Generated by Django 6.0.1 on 2026-01-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(default='km', max_length=20)),
                ('interval_value', models.PositiveIntegerField(default=1000)),
                ('last_service_km', models.PositiveIntegerField(default=0)),
                ('last_service_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_km', models.PositiveIntegerField(default=0)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='vehicles.vehicle')),
            ],
        ),
    ]
