# Generated by Django 6.0.1 on 2026-02-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='active',
            new_name='is_active',
        ),
    ]
