# Generated by Django 6.0.1 on 2026-03-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='active',
            new_name='is_active',
        ),
    ]
